services:
  - type: web
    name: oelp-backend
    env: python
    plan: free
    buildCommand: |
      cd oelp_backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: |
      cd oelp_backend && python manage.py migrate && gunicorn oelp_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: oelp-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: oelp-db
          property: connectionString

databases:
  - name: oelp-db
    plan: free
